#!/bin/bash
# akm-init.sh — Source this file in your .bashrc to enable AKM session lifecycle
# and LLM tool wrappers (claude, copilot, opencode, pi).
#
# Generated by: akm setup
# Do not edit directly — changes will be overwritten on next `akm setup`.
#
# Usage (added automatically by akm setup):
#   source ~/.local/share/akm/shell/akm-init.sh
#
# NOTE: No `set -euo pipefail` here. This file is sourced into the user's
# interactive shell — setting -e would cause the shell to exit on any error.
# Individual functions handle errors with `|| true` and explicit return codes.

# --- Config ---

# Reads config via the akm binary's proper TOML parser.
# This avoids fragile grep/sed parsing and eliminates the jq dependency.
# Each value is cached in a shell variable for the session lifetime.
#
# Note: `akm config <key>` prints "(not set)" for unset values.
# We guard against this with explicit empty-check fallbacks.
_akm_load_config() {
  local raw
  raw="$(akm config features 2>/dev/null || true)"
  _AKM_FEATURES="${raw}"
  [[ "$_AKM_FEATURES" == "(not set)" ]] && _AKM_FEATURES=""

  raw="$(akm config artifacts.dir 2>/dev/null || true)"
  _AKM_ARTIFACTS_DIR="${raw}"
  [[ "$_AKM_ARTIFACTS_DIR" == "(not set)" || -z "$_AKM_ARTIFACTS_DIR" ]] && _AKM_ARTIFACTS_DIR="$HOME/.akm/artifacts"

  raw="$(akm config artifacts.auto-push 2>/dev/null || true)"
  _AKM_ARTIFACTS_AUTO_PUSH="${raw}"
  [[ "$_AKM_ARTIFACTS_AUTO_PUSH" == "(not set)" || -z "$_AKM_ARTIFACTS_AUTO_PUSH" ]] && _AKM_ARTIFACTS_AUTO_PUSH="true"
}

_akm_feature_enabled() {
  local feature="$1"
  [[ ",$_AKM_FEATURES," == *",$feature,"* ]]
}

# --- Git helpers ---

_akm_in_git_repo() {
  git rev-parse --is-inside-work-tree &>/dev/null
}

_akm_project_root() {
  git rev-parse --show-toplevel 2>/dev/null || true
}

_akm_repo_name() {
  basename "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null || true
}

# --- Skills session ---

_akm_skills_session_start() {
  local project_root
  project_root="$(_akm_project_root)"
  if [[ -z "$project_root" ]]; then
    return 1
  fi

  local project_name
  project_name="$(_akm_repo_name)"
  local session_id="${project_name:-anon}-$(date +%s)-$$"
  local staging="${XDG_CACHE_HOME:-$HOME/.cache}/akm/$session_id"

  # Create staging directory structure.
  # Pi is included: it has no subagent concept, but keeping the layout uniform
  # keeps this in step with `akm skills load`, which creates both subdirs.
  local tool_dir
  for tool_dir in .claude .copilot .agents .pi; do
    mkdir -p "$staging/$tool_dir"/{skills,agents}
  done

  # Delegate all manifest loading and symlink creation to the Rust binary
  # in a single process invocation (avoids N+1 subprocess overhead).
  akm skills session-setup "$staging" "$project_root" 2>/dev/null || true

  export AKM_SESSION="$staging"
}

_akm_skills_session_end() {
  if [[ -n "${AKM_SESSION:-}" && -d "$AKM_SESSION" ]]; then
    rm -rf "$AKM_SESSION"
  fi
  unset AKM_SESSION
}

# --- Artifacts lifecycle ---

_akm_artifacts_ensure_dir() {
  local artifacts_dir="${_AKM_ARTIFACTS_DIR:-$HOME/.akm/artifacts}"
  local repo_name
  repo_name="$(_akm_repo_name)"

  if [[ -z "$repo_name" ]]; then
    return 1
  fi

  local artifact_dir="$artifacts_dir/$repo_name"
  if [[ ! -d "$artifact_dir" ]]; then
    mkdir -p "$artifact_dir"
  fi
  echo "$artifact_dir"
}

_akm_artifacts_pull() {
  local artifacts_dir="${_AKM_ARTIFACTS_DIR:-$HOME/.akm/artifacts}"
  if [[ -d "$artifacts_dir/.git" ]]; then
    git -C "$artifacts_dir" pull --rebase --autostash --quiet 2>/dev/null || true
  fi
}

_akm_artifacts_commit_and_push() {
  local artifacts_dir="${_AKM_ARTIFACTS_DIR:-$HOME/.akm/artifacts}"
  local repo_name
  repo_name="$(_akm_repo_name)"

  if [[ ! -d "$artifacts_dir/.git" ]]; then
    return 0
  fi

  local has_changes=false
  if ! git -C "$artifacts_dir" diff --quiet 2>/dev/null; then
    has_changes=true
  fi
  if [[ -n "$(git -C "$artifacts_dir" ls-files --others --exclude-standard 2>/dev/null)" ]]; then
    has_changes=true
  fi

  if [[ "$has_changes" == true ]]; then
    git -C "$artifacts_dir" add -A
    git -C "$artifacts_dir" commit -m "${repo_name:-misc}: $(date +%Y-%m-%d-%H%M)" --quiet 2>/dev/null || true
    git -C "$artifacts_dir" pull --rebase --autostash --quiet 2>/dev/null || true
    git -C "$artifacts_dir" push --quiet 2>/dev/null &
  fi
}

# --- Session orchestration ---

_akm_session_start() {
  _akm_load_config

  local artifact_dir=""
  local staging_dir=""

  if _akm_in_git_repo; then
    # Artifacts: pull and ensure project dir
    if _akm_feature_enabled "artifacts"; then
      _akm_artifacts_pull
      artifact_dir="$(_akm_artifacts_ensure_dir)" || true
    fi

    # Skills: create staging dir
    if _akm_feature_enabled "skills"; then
      _akm_skills_session_start
      staging_dir="${AKM_SESSION:-}"
    fi
  fi

  # Bridge artifacts into the staging tree via symlinks.
  # A top-level artifacts/ symlink makes the path obvious to LLMs
  # (they see the staging root as an "additional working directory").
  # Per-tool symlinks are kept for tools that only read their own subdir.
  # Pi is excluded: it never reads the staging root, and it is told the
  # artifact dir by absolute path instead (see the `pi)` branch below).
  if [[ -n "$artifact_dir" && -n "$staging_dir" ]]; then
    ln -sfn "$artifact_dir" "$staging_dir/artifacts"
    local tool_dir
    for tool_dir in .claude .copilot .agents; do
      ln -sfn "$artifact_dir" "$staging_dir/$tool_dir/artifacts"
    done
  fi

  # Export for use in _akm_session_end and _akm_wrap_tool
  export _AKM_ARTIFACT_DIR="${artifact_dir}"
  export _AKM_STAGING_DIR="${staging_dir}"
}

_akm_session_end() {
  # Config vars (_AKM_FEATURES, _AKM_ARTIFACTS_AUTO_PUSH) persist from
  # _akm_session_start — no need to reload.

  # Skills cleanup
  if [[ -n "${_AKM_STAGING_DIR:-}" ]]; then
    _akm_skills_session_end
  fi

  # Artifacts: commit and push if auto-push enabled
  if _akm_feature_enabled "artifacts" && [[ "${_AKM_ARTIFACTS_AUTO_PUSH:-true}" == "true" ]]; then
    if _akm_in_git_repo; then
      _akm_artifacts_commit_and_push
    fi
  fi

  unset _AKM_ARTIFACT_DIR _AKM_STAGING_DIR
}

# --- Pi helpers ---

# Pi's config dir, honouring its own override.
_akm_pi_agent_dir() {
  echo "${PI_CODING_AGENT_DIR:-$HOME/.pi/agent}"
}

# Pi's own APPEND_SYSTEM.md, if any (project wins over global — same order Pi uses).
#
# Passing --append-system-prompt on the command line *replaces* the file Pi
# would otherwise discover, so the wrapper has to re-pass it explicitly or the
# user's append prompt silently disappears.
_akm_pi_append_file() {
  if [[ -f "$PWD/.pi/APPEND_SYSTEM.md" ]]; then
    echo "$PWD/.pi/APPEND_SYSTEM.md"
  elif [[ -f "$(_akm_pi_agent_dir)/APPEND_SYSTEM.md" ]]; then
    echo "$(_akm_pi_agent_dir)/APPEND_SYSTEM.md"
  fi
}

# The artifacts announcement appended to Pi's system prompt.
#
# Pi has no --add-dir, and needs none: its tools are not sandboxed to the
# working directory. The artifacts dir only has to be named.
_akm_pi_artifacts_prompt() {
  cat <<EOF
## AKM artifacts directory

$_AKM_ARTIFACT_DIR

That absolute path is this project's AKM artifacts directory. It lives outside
the repository and holds non-code outputs: plans/, research/, sessions/,
prompts/, archive/. Write plans, research and session notes there rather than
into the repository, and read from it with absolute paths.
EOF
}

# --- Tool wrapper ---

_akm_wrap_tool() {
  local tool="$1"; shift

  _akm_session_start

  local cmd=(command "$tool")

  case "$tool" in
    opencode)
      # opencode uses OPENCODE_CONFIG_DIR instead of --add-dir.
      # Artifacts are symlinked into the staging dir (see _akm_session_start).
      if [[ -n "${_AKM_STAGING_DIR:-}" ]]; then
        export OPENCODE_CONFIG_DIR="${_AKM_STAGING_DIR}/.agents"
      fi
      ;;
    pi)
      # Pi has no --add-dir. Session skills mount explicitly with --skill
      # (repeatable, and Pi follows symlinked skill directories); the artifacts
      # dir is announced in the system prompt rather than mounted.
      if [[ -n "${_AKM_STAGING_DIR:-}" && -d "${_AKM_STAGING_DIR}/.pi/skills" ]]; then
        cmd+=(--skill "${_AKM_STAGING_DIR}/.pi/skills")
      fi
      if [[ -n "${_AKM_ARTIFACT_DIR:-}" ]]; then
        local pi_append
        pi_append="$(_akm_pi_append_file)"
        [[ -n "$pi_append" ]] && cmd+=(--append-system-prompt "$pi_append")
        cmd+=(--append-system-prompt "$(_akm_pi_artifacts_prompt)")
      fi
      ;;
    *)
      # claude, copilot, vibe support --add-dir.
      # Artifacts are symlinked into the staging dir, so one dir is enough.
      # If only artifacts (no skills/staging), pass the artifact dir directly.
      if [[ -n "${_AKM_STAGING_DIR:-}" ]]; then
        cmd+=(--add-dir "$_AKM_STAGING_DIR")
      elif [[ -n "${_AKM_ARTIFACT_DIR:-}" ]]; then
        cmd+=(--add-dir "$_AKM_ARTIFACT_DIR")
      fi
      ;;
  esac

  cmd+=("$@")

  "${cmd[@]}"
  local exit_code=$?

  unset OPENCODE_CONFIG_DIR 2>/dev/null || true
  _akm_session_end
  return $exit_code
}

# --- Exported wrappers ---
# claude, copilot get the staging dir (which includes artifacts via symlink)
# with --add-dir; opencode uses OPENCODE_CONFIG_DIR; pi uses --skill plus a
# system-prompt note naming the artifacts dir.
# Vibe is excluded (doesn't support --add-dir).

claude()   { _akm_wrap_tool claude   "$@"; }
copilot()  { _akm_wrap_tool copilot  "$@"; }
opencode() { _akm_wrap_tool opencode "$@"; }
pi()       { _akm_wrap_tool pi       "$@"; }
